# Dynamic DockerFile application file for abcdesktop.io generated by https://github.com/abcdesktopio/abcdesktopio/oc.apps/make.js
# DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
# Dockerfile devsecops is generated at Wed Oct 15 2025 00:43:39 GMT+0000 (Coordinated Universal Time)
# platforms=linux/amd64,linux/arm64
#
ARG TAG=4.2
FROM ghcr.io/abcdesktopio/oc.template.ubuntu.24.04:$TAG
USER root
ENV ABCDESKTOP_LOCALACCOUNT_DIR=/etc/localaccount
# Install package
RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y wget konsole sudo bash openssh-client telnet sshcommand sshfs ftp-ssl wput curl wget ncftp git git-ftp ftp dbus-x11 cloc bandit python3-bandit gcc make python3-pip python3-virtualenv golang-go python3-venv pre-commit build-essential libc6-dev && apt-get clean && rm -rf /var/lib/apt/lists/* 
# End of install package
LABEL oc.icon="circle_security.svg"
LABEL oc.icondata="PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4NCjwhLS0gR2VuZXJhdG9yOiBBZG9iZSBJbGx1c3RyYXRvciAxOS4xLjAsIFNWRyBFeHBvcnQgUGx1Zy1JbiAuIFNWRyBWZXJzaW9uOiA2LjAwIEJ1aWxkIDApICAtLT4NCjxzdmcgdmVyc2lvbj0iMS4xIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB4PSIwcHgiIHk9IjBweCINCgkgdmlld0JveD0iMCAwIDY0IDY0IiBzdHlsZT0iZW5hYmxlLWJhY2tncm91bmQ6bmV3IDAgMCA2NCA2NDsiIHhtbDpzcGFjZT0icHJlc2VydmUiPg0KPHN0eWxlIHR5cGU9InRleHQvY3NzIj4NCgkuc3Qwe2ZpbGw6I0M3NUM1Qzt9DQoJLnN0MXtvcGFjaXR5OjAuMjt9DQoJLnN0MntmaWxsOiMyMzFGMjA7fQ0KCS5zdDN7ZmlsbDojRjVDRjg3O30NCgkuc3Q0e2ZpbGw6I0UwOTk1RTt9DQo8L3N0eWxlPg0KPGcgaWQ9IkxheWVyXzEiPg0KCTxnPg0KCQk8Y2lyY2xlIGNsYXNzPSJzdDAiIGN4PSIzMiIgY3k9IjMyIiByPSIzMiIvPg0KCTwvZz4NCgk8ZyBjbGFzcz0ic3QxIj4NCgkJPHBhdGggY2xhc3M9InN0MiIgZD0iTTMyLDU2YzAsMC0xOC02LjgtMTgtMjEuNVYyMC45YzAsMCw1LjgtNi45LDE4LTYuOVY1NnoiLz4NCgk8L2c+DQoJPGcgY2xhc3M9InN0MSI+DQoJCTxwYXRoIGNsYXNzPSJzdDIiIGQ9Ik0zMiw1NmMwLDAsMTgtNi44LDE4LTIxLjVWMjAuOWMwLDAtNS44LTYuOS0xOC02LjlWNTZ6Ii8+DQoJPC9nPg0KCTxnPg0KCQk8cGF0aCBjbGFzcz0ic3QzIiBkPSJNMzIsNTRjMCwwLTE4LTYuOC0xOC0yMS41VjE4LjljMCwwLDUuOC02LjksMTgtNi45VjU0eiIvPg0KCTwvZz4NCgk8Zz4NCgkJPHBhdGggY2xhc3M9InN0NCIgZD0iTTMyLDU0YzAsMCwxOC02LjgsMTgtMjEuNVYxOC45YzAsMC01LjgtNi45LTE4LTYuOVY1NHoiLz4NCgk8L2c+DQo8L2c+DQo8ZyBpZD0iTGF5ZXJfMiI+DQo8L2c+DQo8L3N2Zz4NCg=="
LABEL oc.keyword="devsecops,konsole,terminal,bash,shell,cmd,admin,ftp,telnet,netcat,sshfs,curl,wget,git,ssh"
LABEL oc.cat="TerminalEmulator"
LABEL oc.desktopfile="org.kde.konsole.desktop"
LABEL oc.desktopfileoverwrited="org.kde.konsole.devsecops.desktop"
LABEL oc.wm_class="konsole"
LABEL oc.launch="konsole.konsole"
LABEL oc.template="ghcr.io/abcdesktopio/oc.template.ubuntu.24.04"
LABEL oc.name="devsecops"
LABEL oc.displayname="DevSecOps"
LABEL oc.path="/usr/bin/konsole"
LABEL oc.type=app
LABEL oc.showinview="dock"
LABEL oc.rules="{\"homedir\":{\"default\":true}}"
LABEL oc.acl="{\"permit\":[\"all\"]}"
ENV APPNAME="devsecops"
ENV APPBIN="/usr/bin/konsole"
# ENV APP is deprecated, removed in next release
ENV APP="/usr/bin/konsole"
ENV SHELL=/bin/bash
SHELL [ "/bin/bash", "-c" ]
RUN echo "ALL ALL=(ALL:ALL) ALL">/etc/sudoers.d/all
RUN wget https://github.com/trufflesecurity/trufflehog/releases/download/v3.90.8/trufflehog_3.90.8_linux_amd64.tar.gz && tar -xvf trufflehog_3.90.8_linux_amd64.tar.gz && mv trufflehog /usr/local/bin && rm -rf trufflehog_3.90.8_linux_amd64.tar.gz
RUN git clone https://github.com/gitleaks/gitleaks.git && cd gitleaks && make build
RUN mkdir semgrep && virtualenv semgrep && source semgrep/bin/activate && pip3 install semgrep
#
# Permit to create file in directory /var/lib/dbus/
RUN if [ -x /usr/bin/dbus-launch ]; then chmod g+r,g+w,o+r,o+w /var/lib/dbus ; fi

# Create links for local acccounts
# /etc/passwd  -> /etc/localaccount/passwd
# /etc/group   -> /etc/localaccount/group
# /etc/shadow  -> /etc/localaccount.shadow/shadow
# /etc/gshadow -> /etc/localaccount.shadow/gshadow
RUN mkdir -p ${ABCDESKTOP_LOCALACCOUNT_DIR} ${ABCDESKTOP_LOCALACCOUNT_DIR}.shadow
RUN for f in passwd group ;   do if [ -f /etc/$f ] ; then  cp /etc/$f ${ABCDESKTOP_LOCALACCOUNT_DIR};        rm -f /etc/$f; ln -s ${ABCDESKTOP_LOCALACCOUNT_DIR}/$f        /etc/$f; fi; done
RUN for f in shadow gshadow ; do if [ -f /etc/$f ] ; then  cp /etc/$f ${ABCDESKTOP_LOCALACCOUNT_DIR}.shadow; rm -f /etc/$f; ln -s ${ABCDESKTOP_LOCALACCOUNT_DIR}.shadow/$f /etc/$f; fi; done
CMD [ "/composer/appli-docker-entrypoint.sh" ]
