name: CI build app list

on:
  schedule:
    - cron: '0 0 * * 0-6'

  workflow_dispatch:

jobs:
  build_app_list:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install jq cli
        run: sudo apt-get install -y jq

      - name: Build app list
        run: |
          ./buildAppList.sh

      - name: Upload app list
        uses: actions/upload-artifact@v4
        with:
          name: appLists
          path: ./appLists

      # - name: Upload app to release 
      #   uses: svenstaro/upload-release-action@v2
      #   with:
      #     repo_token: ${{ secrets.GITHUB_TOKEN }}
      #     file: ./appLists/*
      #     file_glob: true
      #     tag: appLists
      #     overwrite: true

  commit_current_repo:
    runs-on: ubuntu-latest
    needs: build_app_list
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download app list
        uses: actions/download-artifact@v4
        with:
          name: appLists
          path: appLists/

      - name: Test downloaded artifact
        run: ls -R

      - name: Add and commit to main
        run: |
          git config user.name "applists-builder[bot]"
          git config user.email "41898282+applists-builder[bot]@users.noreply.github.com"
          git add appLists
          git commit -m "Update app lists"
          git push