name: CI build app list

on:
  schedule:
    - cron: '0 0 * * 7'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install jq cli
        run: sudo apt-get install -y jq

      - name: Build app list
        run: |
          ./buildAppList.sh

      # - name: Upload app list
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: appLists
      #     path: ./appLists

      - name: Upload app to release 
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./appLists.json
          file_glob: true
          tag: appLists
          overwrite: true